### ISSUE TITLE
Update Ubuntu

### ISSUE THREAD

**Issue by Slohrsh** [vvirag/latex4bitbucket#1]
Due to this update issue https://ubuntuforums.org/showthread.php?t=2382832
please update ubuntu to 7.10

**Comment by vvirag** [comment]
Thanks for the heads up. Fortunately the description under `readme` on _how to use the (earlier generated) docker image_ still stands, as that image was built when this docker file was still valid.

I'll update to the latest Ubuntu but I'm still hesitant on merging your pull request. I understand that in given projects it makes sense to reduce the container size, but I tried to keep this docker file itself as generic as possible (referring to the number of latex packages to be installed).

**Comment by Slohrsh** [comment]
Hi, I'm sorry the additional commits wasn't ment for you. The only thing i wanted to merge is the update of the version number. In addition I would like to recommend to use the :latest tag instead of a specific version. With that you will avoid further tickets like that.
cheers
